### ISSUE TITLE
VT100 emulator with 8080 and ROMs

### ISSUE THREAD

**Issue by larsbrinkhoff** [mattiase/wraptest#2]
Here is a VT100 emulator with 8080 and ROMs:  
https://github.com/phooky/VT100-Hax

**Comment by mattiase** [comment]
Thank you! This emulator nicely confirms the VT100 behaviour reported previously – very useful. I was initially worried that the ncurses interface would somehow leak semantics of the underlying terminal, but those concerns were probably unfounded.

**Comment by larsbrinkhoff** [comment]
Yes, there is that.  There's a half-done QT frontend as well, but I suspect it will not be brought up to date.
