### ISSUE TITLE
XTerm results shows it's correct.

### ISSUE THREAD

**Issue by RealDeuce** [mattiase/wraptest#3]
Your readme states that "No emulator tested so far matches either actual hardware or the specification in STD-070, but some are clearly better than others." but the XTerm column in the results exactly matches the VT-420, which is the terminal XTerm emulates by default.

It would also be interesting to see the XTerm results when set to the other modes XTerm supports (especially VT-220)... you can specify the term id using the -ti parameter on the command-line:

xterm -ti vt100
xterm -ti vt220

To match what you have listed... other IDs are vt52, vvt101, vt102, and vt240.

**Comment by mattiase** [comment]
Right, that text was written before XTerm changed its behaviour. Thanks for pointing it out! I have now made a correction.

The -ti parameter does not seem to affect XTerm's behaviour in this respect (I tried the latest snapshot).
